# Blind doctrine picks — SPXW 7/21 (committed BEFORE seeing Glitch's plays)

Made from the 1-min replay (SPXW/SPY/QQQ, session B), doctrine applied cold. I have NOT
seen Glitch's 7/21 plays. Committed to git as the timestamp.

## Call: BULLISH / LONG — high conviction (the mirror of 7/20)

### The read (charts-first → GEX)
- **Price:** opened **at the low 7443** (= 7/20's close zone), rallied straight up to **7515 by ~12:56**,
  then **pinned 7507–7512** into the close (+0.86%). Higher highs/lows all morning = uptrend.
- **Open = SLINGSHOT / trend-up:** 09:30 was **negative gamma** (netG −44) with a **barney at 7455 above
  spot** (−12M) = acceleration fuel overhead. Price at the low + −GEX above + a floor building below =
  **−GEX-over-+GEX slingshot → long the break up.**
- **King ABOVE spot all day** (7520 pika), **growing rapidly** 16M → 44 → 82 → **177M** by 14:00 = the
  **magnet.** Doctrine: *trade toward the king, not through it* → long toward 7520.
- **Rolling floor UP:** 7425 → 7450 → 7475 → 7495 → 7505 (5 consecutive higher floors = well past the
  "3 = confirmation" bar) = **bullish structural trend.**
- **Trinity ALIGNED UP:** SPY +0.82% (100% +gamma), **QQQ +1.85%** (95% +gamma), SPX +0.86%. Clean
  directional confluence — not a chop/whipsaw day.

### THE PICKS
| | |
|---|---|
| **Bias** | **BULLISH / long** (high conviction) |
| **Instrument** | SPXW 0DTE **calls** |
| **Strike zone** | **7450–7500C** (ATM at the open ~7450, riding up with the rolling floor) |
| **Entry** | near the **open (7443–7480)** — long the slingshot break up through the 7455 barney, and/or buy taps of the **rising floor**; conviction from trinity |
| **Target** | the **7520 king pika** (the magnet). Price ran 7443 → 7515 and pinned there |
| **Timing** | a **MORNING long**, booked by ~13:00 at the 7520 pin — don't chase above the king |
| **Exit** | take profit at/near 7515–7520 (king became a 177M pin; price stalled) |

### What we would NOT take
- Any **puts / bear reversals** — fighting an up-trend + rolling floor up + king above + trinity-up.
- Any **short into the rising floor**, any mid-range fade.
- Nothing after 15:15 ET.

### EXECUTED PLAY LIST — real SPXW call fills (UW intraday), LONG, exit at the 7520 king ~13:00
| Strike | Entry ~9:35 | Exit ~13:00 | Return | Peak 12:54 |
|---|---|---|---|---|
| 7450C | $37.90 | $63.00 | **+66%** | +70% |
| 7475C | $19.40 | $38.90 | **+100%** | +111% |
| 7500C | $6.70 | $15.60 | **+133%** | +163% |
| 7515C | $2.63 | $5.17 | **+96%** | +143% (held-to-close −98%: pin left it OTM) |

Exit lesson: target = a king/pika = a PIN. Price hit 7515 @12:54, king → 177M, pinned 7507–7512 rest of
day. Exit AT the king = +66–133%; holding past it bleeds (7515C $6.40→$0.05). The +45% cap would've been
too tight today (booked +45% vs the +133% the "exit at the target node" rule caught).

### Honest caveats
- Post-close (I saw the path), but **blind to Glitch** — the test. Glitch posted no Talon 7/21 anyway.
- Our LIVE tracker got **0 fires on 7/21** (two-process cookie clobber) — this is the *doctrine's* call on
  real data, not what our system fired. Reproducing live needs one clean session at 9:30 + doctrine wired in.
